version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn Server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    networks:
      - web_network
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
    - web_network

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6378:6379'
    volumes:
      - redisdata:/var/lib/redis/data/
    networks:
      - web_network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles/
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - web_network
      
volumes:
  postgres_data: 
  static_volume:
  redisdata:

networks:
  web_network: