# Generated by Django 4.0.6 on 2022-08-24 08:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('activation_time', models.DateTimeField()),
                ('serial_number', models.CharField(max_length=255)),
                ('flight_controller_id', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('aircraft_lock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FlightMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_area', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('spraying_rate', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), size=None)),
                ('task_flight_speed', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), null=True, size=None)),
                ('height', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), size=None)),
                ('hopper_outlet_size', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), size=None)),
                ('spinner_disk_speed', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), size=None)),
                ('location', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), size=None), size=None)),
                ('take_off_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Realtime.aircraft')),
                ('flight_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Realtime.flightmode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Realtime.aircrafttype'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Account.team'),
        ),
    ]
