# Generated by Django 4.0.6 on 2022-09-18 19:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtime', '0002_alter_realtime_aircraft_alter_realtime_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtime',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='height',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='hopper_outlet_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='spinner_disk_speed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='spraying_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='task_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='task_flight_speed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
    ]
