# Generated by Django 4.0.6 on 2022-09-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtime', '0003_alter_realtime_data_alter_realtime_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtime',
            name='landing_time',
            field=models.DateTimeField(null=True),
        ),
    ]
