# Generated by Django 4.0.6 on 2022-08-08 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0012_alter_user_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('activation_time', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.CharField(max_length=255)),
                ('flight_controller_id', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('Aircraft_lock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1', models.FloatField()),
                ('value_2', models.FloatField()),
                ('value_3', models.FloatField()),
                ('value_4', models.FloatField()),
                ('value_5', models.FloatField()),
                ('value_6', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('spraying_rate', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('route_spacing', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('task_flight_speed', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('height', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('hopper_outlet_size', models.IntegerField()),
                ('spinner_disk_speed', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('take_off_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
                ('flight_duration', models.DateTimeField()),
                ('flight_record', models.CharField(max_length=255)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Realtime.aircraft')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Realtime.data')),
                ('flight_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Realtime.flightmode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Realtime.aircrafttype'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.team'),
        ),
    ]
