# Generated by Django 4.0.6 on 2022-08-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Realtime', '0002_alter_realtime_data_delete_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='Aircraft_lock',
            new_name='aircraft_lock',
        ),
    ]
