# Generated by Django 4.0.6 on 2022-08-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Realtime', '0003_rename_aircraft_lock_aircraft_aircraft_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='team',
        ),
    ]
