# Generated by Django 4.0.6 on 2022-08-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_alter_user_team'),
        ('Realtime', '0004_remove_aircraft_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Account.team'),
        ),
    ]
