# Generated by Django 4.0.6 on 2022-08-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtime', '0005_aircraft_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='activation_time',
            field=models.DateTimeField(),
        ),
    ]
