# Generated by Django 4.0.6 on 2022-08-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Realtime', '0006_alter_aircraft_activation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtime',
            old_name='task',
            new_name='task_area',
        ),
    ]
