# Generated by Django 4.0.6 on 2022-08-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtime', '0007_rename_task_realtime_task_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtime',
            name='height',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='route_spacing',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='spraying_rate',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='task_area',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='realtime',
            name='task_flight_speed',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
    ]
