# Generated by Django 4.0.6 on 2022-08-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_team_alter_user_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team_id',
            new_name='team',
        ),
    ]
