# Generated by Django 4.0.6 on 2022-08-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
    ]
